### PR TITLE
Accepting content html beyond the path

### PR DESCRIPTION
**Pull request by luizalexandrew**
Example:

let content = `
     <div>
           ...
    </div>
`

es6Renderer({html: content}, ...)

### CODE REVIEW

**Comment by dondido** [comment]
How about this:
```
const titleTpl = '${engineName} - The fastest javascript template string engine!';
const cb = (err, content) => err || content;

// sync - second parameter is a string representation of an array of variable names.
// The returned function is called with a string representation of an array of variable values.
const compiled = es6Renderer(titleTpl, 'engineName')('ES6 Renderer');
```

**Comment by luizalexandrew** [comment]
I didn't understand what you said, sorry.

What I needed to do was the following, instead if express-es6-template-engine only accepts the path it can also accept an html file previously loaded by fs

Example:

 fs.readFile(config.Page, 'utf8', function(err, contentLoaded) {
....
...
contents // Some actions I will take on content
...
...
...
es6Renderer(contentLoaded, .... )

With the current code is it possible to do this?

**Comment by dondido** [comment]
It works exactly the way you posted:

```
fs.readFile(config.Page, 'utf8', function(err, content) {
    contents // Some actions I will take on content
    es6Renderer(content, .... )
});
```

**Comment by luizalexandrew** [comment]
I did this example by passing a response from fs.readFile (For example, the application I'm using does some operations before calling es6Renderer)

image

That was the answer I got in the execution, what do I need to do to work as you mentioned? Apparently es6Renderer thinks I'm passing a path instead of html content in a file

image

**Comment by dondido** [comment]
Ok I see, can yout try with the following:
```
// async - second parameter is an object and third parameter is a callback function
es6Renderer(contentFile, { template: true, locals:{ ... } }, callback);
```

**Pull request closed without merging**
